[package]
name = "tact-parser"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
hex.workspace = true
modular-bitfield.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
clap = { workspace = true, features = ["derive", "cargo", "env"] }
criterion.workspace = true
tracing-subscriber.workspace = true

[[bench]]
name = "jenkins3"
harness = false
