[workspace]
members = [
  "ngdp-bpsv",
  "ngdp-cache",
  "ngdp-cdn",
  "ngdp-crypto",
  "ribbit-client",
  "tact-client",
  "tact-parser",
  "ngdp-client", "blte",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Daniel S. Reichenbach <daniel@kogit.network>"]
edition = "2024"
rust-version = "1.86"
license = "MIT OR Apache-2.0"
repository = "https://github.com/wowemulation-dev/cascette-rs"
homepage = "https://github.com/wowemulation-dev/cascette-rs"

[workspace.dependencies]
byteorder = "1.5"
clap = "4.5"
criterion = "0.6"
dirs = "6.0"
hex = "0.4.3"
modular-bitfield = "0.12.0"
rand = "0.9"
serde = "1.0"
thiserror = "2.0"
tokio = "1.45"
tracing = "0.1"
tracing-subscriber = "0.3"
