[workspace]
members = [
  "ngdp-bpsv",
  "ngdp-cache",
  "ngdp-cdn",
  "ngdp-crypto",
  "ribbit-client",
  "tact-client",
  "tact-parser",
  "ngdp-client",
  "blte",
  "casc-storage", 
  "ngdp-patch",
  "test-utils",
]
resolver = "2"

[workspace.package]
version = "0.4.3"
authors = ["Daniel S. Reichenbach <daniel@kogit.network>"]
edition = "2024"
rust-version = "1.86"
license = "MIT OR Apache-2.0"
repository = "https://github.com/wowemulation-dev/cascette-rs"
homepage = "https://github.com/wowemulation-dev/cascette-rs"

[workspace.dependencies]
byteorder = "1.5"
clap = "4.5"
criterion = "0.7"
dirs = "6.0"
hex = "0.4.3"
modular-bitfield = "0.12.0"
rand = "0.9"
serde = "1.0"
tempfile = "3.20"
thiserror = "2.0"
tokio = "1.47"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
