[workspace]
members = ["tact-client", "ribbit-client", "ngdp-bpsv", "ngdp-client"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Daniel S. Reichenbach <daniel@kogit.network>"]
edition = "2024"
rust-version = "1.86"
license = "MIT OR Apache-2.0"
repository = "https://github.com/wowemulation-dev/cascette-rs"
homepage = "https://github.com/wowemulation-dev/cascette-rs"

[workspace.dependencies]
clap = "4.5"
criterion = "0.6"
dirs = "6.0"
serde = "1.0"
thiserror = "2.0"
tokio = "1.45"
tracing = "0.1"
tracing-subscriber = "0.3"
